{% set version = '1.2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sbtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sbtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sbtools/sbtools_{{ version }}.tar.gz
  sha256: 8aa76f49df7f2133ed5289e006f39f09898915f187a0e685e711efa853b27ab1

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-cli
    - r-curl
    - r-httr >=1.0.0
    - r-jsonlite
    - r-keyring
    - r-mime

  run:
    - r-base
    - r-cli
    - r-curl
    - r-httr >=1.0.0
    - r-jsonlite
    - r-keyring
    - r-mime

test:
  commands:
    - $R -e "library('sbtools')"           # [not win]
    - "\"%R%\" -e \"library('sbtools')\""  # [win]

about:
  home: https://github.com/DOI-USGS/sbtools
  license: CC0-1.0
  summary: Tools for interacting with U.S. Geological Survey ScienceBase <https://www.sciencebase.gov>
    interfaces. ScienceBase is a data cataloging and collaborative data management platform.
    Functions included for querying ScienceBase, and creating and fetching datasets.
  license_family: CC
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Package: sbtools
# Title: USGS ScienceBase Tools
# Maintainer: David Blodgett <dblodgett@usgs.gov>
# Version: 1.2.0
# Authors@R: c(person("David", "Blodgett", role=c("cre"), email = "dblodgett@usgs.gov"), person("Luke", "Winslow", role = c("aut"), email = "lawinslow@gmail.com"), person("Scott", "Chamberlain", role = c("ctb"), email = "scott@ropensci.org"), person("Alison", "Appling", role = c("ctb"), email = "aappling@usgs.gov"), person("Jordan", "Read", role   = c("ctb"), email = "jread@usgs.gov"))
# Description: Tools for interacting with U.S. Geological Survey ScienceBase <https://www.sciencebase.gov> interfaces. ScienceBase is a data cataloging and collaborative data management platform. Functions included for querying ScienceBase, and creating and fetching datasets.
# Imports: jsonlite, curl, httr (>= 1.0.0), methods, mime, utils, cli, keyring
# Suggests: testthat, xml2, sf, sp, tools
# License: CC0
# URL: https://github.com/DOI-USGS/sbtools
# BugReports: https://github.com/DOI-USGS/sbtools/issues
# RoxygenNote: 7.2.3
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2023-04-30 22:24:01 UTC; dblodgett
# Author: David Blodgett [cre], Luke Winslow [aut], Scott Chamberlain [ctb], Alison Appling [ctb], Jordan Read [ctb]
# Repository: CRAN
# Date/Publication: 2023-04-30 23:00:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
